[{
    'name': 'Мопс',
    'height': '27-36',
    "ves" : "6.3-8.1",
    "naznachenie" : "Дом",
    "Sherst" : "Глад",
    "Agrassive" : "2",
},
{
    'name': 'Ретривер',
    'height': '52-61',
    "ves" : "26-40",
    "naznachenie" : "Охота",
    "Sherst" : "Плот Вод" , 
    "Agrassive" : "1" ,
},
{
    'name': 'Рассер терьер',
    'height': '22-30',
    "ves" : "5-6",
    "naznachenie" : "Охота",
    "Sherst" : "Глад",
    "Agrassive" : "4",
},
{
    
    'name': 'Немецкая овчарка',
    'height': '55-65',
    "ves" : "22-40",
    "naznachenie" : "Служ",
    "Sherst" : "Плот",
    "Agrassive" : "3",
},
{
    'name': 'Английский бульдог',
    'height': '50-55',
    "ves" : "24",
    "naznachenie" : "Дом",
    "Sherst" : "Глад",
    "Agrassive" : "2",
},
{
    'name': 'Акита-ину',
    'height': '60-70',
    "ves" : "20-40",
    "naznachenie" : "Охот",
    "Sherst" : "Плот",
    "Agrassive" : "2",
},
{
    'name': 'Сербернар',
    'height': '65-85',
    "ves" : "70-85",
    "naznachenie" : "Служ",
    "Sherst" : "Плот",
    "Agrassive" : "2",
},
{
    'name': 'Хаски',
    'height': '50-60',
    "ves" : "15-28",
    "naznachenie" : "Служ",
    "Sherst" : "Плот",
    "Agrassive" : "5",
},
{
    'name': 'Бигль',
    'height': '33-40',
    "ves" : "9-14",
    "naznachenie" : "Охота",
    "Sherst" : "Глад",
    "Agrassive" : "1",
},
{
    'name': 'Шпиц',
    'height': '40-50',
    "ves" : "17-22",
    "naznachenie" : "Дом",
    "Sherst" : "Плот",
    "Agrassive" : "3",
},
{
    'name': 'Доберман',
    'height': '63-72',
    "ves" : "32-45",
    "naznachenie" : "Служ",
    "Sherst" : "Корот",
    "Agrassive" : "3",
},
{
    'name': 'Бультерьер',
    'height': '47-56',
    "ves" : "23-38",
    "naznachenie" : "Дом",
    "Sherst" : "Глад",
    "Agrassive" : "5",
},
{
    'name': 'Далматинец',
    'height': '54-62',
    "ves" : "24-32",
    "naznachenie" : "Охот дом",
    "Sherst" : "Корот",
    "Agrassive" : "4",
},
{
    'name': 'Ротвейлер',
    'height': '56-68',
    "ves" : "38-53",
    "naznachenie" : "Служ",
    "Sherst" : "Глад",
    "Agrassive" : "5",
},
{
    'name': 'Cиба-ину',
    'height': '35-41', 
    "ves" : "7-13",
    "naznachenie" : "Охот",
    "Sherst" : "Плот",
    "Agrassive" : "6",
},
{
    'name': 'Ньюфаундленд',
    'height': '61-76', 
    "ves" : "49-53",
    "naznachenie" : "Служ",
    "Sherst" : "Плот вод",
    "Agrassive" : "2",
}
]
